redis:
  image: xdevelsistemas/debian-env:redis-env
  ports:
    - "6379:6379"
  volumes:
    - "/opt/dockerdata/redis:/data"

mongodb:
  image: xdevelsistemas/debian-env:mongodb-env
  ports:
    - "27017:27017"
  volumes:
    - "/opt/dockerdata/mongo:/data/db"
  command: mongod --smallfiles

